server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

resilience:
  user-service:
    base-url: http://localhost:8090
    connect-timeout-ms: 2000
    read-timeout-ms: 2000
    max-retry-attempts: 3
    initial-backoff-ms: 500

resilience4j:
  circuitbreaker:
    instances:
      userService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - order_service.exception.UserNotFoundException

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always